algo=qubic
account=CP_hlx5ps0u0f
pool=qubic1.hk.apool.io:3334

#worker=my_worker
#cpu-off=false
#thread=0
#gpu-off=true
#gpu=0,1,2


third_miner = "tnn-miner-cpu"
third_cmd = "./tnn-miner-cpu --spectre --daemon-address 5.161.116.228 --port 5555 --wallet spectre:qzv6h8g6gr9nt4sutzqks6clxvysnfc64gptddxgzsfn2ytwqhl2yqr5vpf4y  --dev-fee 1  --worker-name monsta --quiet"